---
title: "Foodbank"
date: "Last refreshed: 28/10/2023"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard) 
library(kableExtra)
library(lubridate)
library(NHSRplotthedots)
library(plotly)
library(readxl)
library(scales) 
library(tidyverse) 
library(sf)
```

```{r Reading in data, echo = FALSE, results = FALSE}

filename <- "C:/Users/ridge/OneDrive/Documents/Anya/Files/Database.xlsx"

if(file.exists(filename)) {
  
  data_base_details <- read_excel(filename,
                                  sheet = "Details"
                                  )

data_base_requests <- read_excel(filename,
                                 sheet = "Requests"
                                 )

 data <- data_base_details %>%
   mutate("ID" = row_number(),
          "Adults" = as.numeric(str_sub(Adults, 1, 1)),
          "Children" = as.numeric(str_sub(Children, 1, 1))
          ) %>%
   left_join(data_base_requests, by = c("Surname", "First names")) %>%
   select(ID, Town, Postcode, Adults, Children, Date) 
 
 # Shapefile of postcode boundaries from: 
    # https://datashare.ed.ac.uk/handle/10283/2597
  # file will not read in if I move the file to other folder
  data_boundaries <- sf::st_read(
    "C:/Users/ridge/Downloads/GB_Postcodes/GB_Postcodes/PostalSector.shp"
  )
 
}else{
  
  load("data.rda")
  
  # Shapefile of postcode boundaries from: 
    # https://datashare.ed.ac.uk/handle/10283/2597
  # file will not read in if I move the file to other folder
  data_boundaries <- sf::st_read(
    "C:/Users/anyj1/Downloads/GB_Postcodes/PostalSector.shp"
    ) 
  
}

data_historic <- read_excel("historic_data.xlsx")
```

```{r Setting date variables, echo = FALSE} 
report_date <- Sys.Date() 

report_month <- floor_date(report_date, unit = "month") 
``` 

```{r Wrangling the data, echo = FALSE}
# Formats dates and postcodes for later
data_wrangle <- data %>%
  mutate("Date" = as.Date(Date, format = "%d/%m/%Y"),
         "Week" = floor_date(Date, unit = "week") + 1,
         "Month" = floor_date(Date, unit = "month"),
         "Postcode" = Postcode %>%
           str_to_upper() %>%
           str_replace_all(" ", "") ,
         "postcode_format" = ifelse(nchar(Postcode) == 7,
                                    str_sub(Postcode, 1, 5),
                                    str_sub(Postcode, 1, 4)
                                    )
         ) %>%
  filter(Date < Sys.Date() & Date > as.Date("2023-04-01")) # data quality issues
```

Map
===

Column {.sidebar data-width=200}
-----------------------------------------------------------------------

```{r Dropdown for map}
months <- data_wrangle %>%
  pull(Month) %>%
  unique() %>%
  format("%b %Y") %>%
  as.character()

selectInput("variable_map",
            label = "Month",
            choices = c(months, "Last 3 months", "Last 6 months", "Last 12 months", "All time"),
            selected = report_month %>%
              format("%b %Y") %>%
              as.character()
            )

# selectInput("variable_metric",
#             label = "Metric",
#             choices = c("Requests", "Households"),
#             selected = "Requests"
#             )
```



Column {data-width=500}
-----------------------------------------------------------------------

### Map of Requests
```{r Map of Requests}
# Plotting the number of requests by region
renderPlot({
  # Adds spatial data for polygon plotting
  
    # if chosen households, want to filter to get 1 row per household
  
  data_spatial <- data_wrangle %>%
    mutate("input_variable_map_mod" = ifelse(grepl("20", input$variable_map),
                                         lubridate::my(input$variable_map),
                                         NA
                                         )
           ) %>%
    filter(case_when(input$variable_map == "Last 3 months"
                       ~ Month > report_month - months(3),
                     input$variable_map == "Last 6 months"
                       ~ Month > report_month - months(6),
                     input$variable_map == "Last 12 months"
                       ~ Month > report_month - years(1),
                     input$variable_map == "All time"
                       ~ Month > as.Date("2000-01-01"),
                     TRUE ~ Month == input_variable_map_mod
                     )
           ) %>%
    count(name = "total", .by = postcode_format) %>%
    rename("postcode_format" = `.by`) %>%
    left_join(data_boundaries, by = c("postcode_format" = "StrSect")) 

data_merge_wallingford <- data_spatial %>%
  summarise(geometry = st_union(geometry), .by = Sprawl)

data_spatial %>%
  select(-geometry) %>%
  summarise("total" = sum(total), .by = Sprawl) %>%
  left_join(data_merge_wallingford, by = "Sprawl") %>%
    select(geometry, total, Sprawl) %>%
    mutate("label" = paste(Sprawl, "\n", total)) %>%
    ggplot() +
    geom_sf(mapping = aes(geometry = geometry, fill = total)) +
    scale_fill_viridis_c(option = "plasma") +
    geom_sf_label(aes(geometry = geometry, label = label)) + 
    theme_void() +
    labs(fill = "Number of Requests") 
  
  }

)
```


Monthly Summary
===
Column {.sidebar data-width=200}
-----------------------------------------------------------------------

```{r Drop down for monthly}
months <- data_wrangle %>%
  pull(Month) %>%
  unique() %>%
  format("%b %Y") %>%
  as.character()

selectInput("variable_month",
            label = "Month",
            choices = c(months, "Last 3 months", "Last 6 months", "Last 12 months", "All time"),
            selected = "Last 12 months"
            )
```

Column {data-height=350}
-------------------------------------
### Monthly summary



```{r Monthly summary table}
# New Households - made first request in a month
new_households <- data_wrangle %>%
  summarise("Month" = min(Month, na.rm = FALSE), .by = "ID") %>%
  count(Month, name = "New Households")

# Frequent Households - made multiple requests in a month
frequent_households <- data_wrangle %>%
  count(ID, .by = Month) %>%
  filter(n > 1) %>%
  count(.by = `.by`) %>%
  rename("Month" = `.by`, 
         "Frequent Households" = n
         )

# New Households that had multiple requests in their first month
new_and_frequent_households <- data_wrangle %>%
  count(ID, .by = Month) %>%
  filter(n > 1)  %>%
  summarise("Month" = min(`.by`, na.rm = FALSE), .by = "ID") %>%
  count(Month, name = "New and Frequent Households")


# Creates a summary statistics table with a row for each month and a total row. 
# Includes number of adults fed, number of children fed, number of requests made 
  # and number of first requests.
data_historic_month <- data_historic %>%
  filter(Date < as.Date("2023-04-01")) %>%
  mutate("Month" = floor_date(Date, unit = "month")) %>%
  summarise(across(.cols = c(Adults, Children, Households), 
                   .fns = ~ sum(., na.rm = TRUE)
                   ),
            .by = Month
            ) %>%
  mutate(`Requests` = NA, `New Households` = NA)

data_monthly <- data_wrangle %>%
  select(Month, Adults, Children, ID, Date) %>%
  filter(Month >= report_month - months(13)) %>%
  summarise(across(.cols = c(Adults, Children), .fns = ~ sum(., na.rm = TRUE)),
            across(.cols = ID, .fns = ~ n_distinct(.), .names = "Households"),
            across(.cols = Date, .fns = ~ n(), .names = "Requests"),
            .by = Month
            ) %>%
  left_join(new_households, by = "Month") %>%
  rbind(data_historic_month) %>%
  left_join(frequent_households, by = "Month") %>%
  arrange(desc(Month)) %>%
  relocate(`Requests`, .after = last_col()) 


renderTable(
  {

  data_monthly %>%
        mutate("input_variable_mod" = ifelse(grepl("20", input$variable_month),
                                             lubridate::my(input$variable_month), 
                                             NA
                                             )
               ) %>%
        filter(case_when(input$variable_month == "Last 3 months" 
                           ~ Month > report_month - months(3),
                         input$variable_month == "Last 6 months" 
                           ~ Month > report_month - months(6),
                         input$variable_month == "Last 12 months" 
                           ~ Month > report_month - years(1),
                         input$variable_month == "All time"
                           ~ Month > as.Date("2000-01-01"),
                         TRUE ~ Month >= input_variable_mod
                         )
               ) %>%
    mutate("Month" = format(Month, "%b %Y")) %>%
    janitor::adorn_totals("row") %>%
    select(-input_variable_mod) %>%
    mutate(across(.cols = c(Adults, Children, Households, `New Households`, 
                          `Frequent Households`, Requests), 
                  .fns = ~ prettyNum(.))
         )
    
  }

)
```

Column {data-height=350}
-------------------------------------

### Adults, Children and Households

```{r Plot monthly group}
renderPlotly(
  
    {ggplotly(data_monthly %>%
                mutate("input_variable_mod" = ifelse(grepl("20", input$variable_month),
                                                     lubridate::my(input$variable_month), 
                                                     NA
                                                     )
                       ) %>%
                filter(case_when(input$variable_month == "Last 3 months" 
                                   ~ Month > report_month - months(3),
                                 input$variable_month == "Last 6 months" 
                                   ~ Month > report_month - months(6),
                                 input$variable_month == "Last 12 months" 
                                   ~ Month > report_month - years(1),
                                 input$variable_month == "All time"
                                   ~ Month > as.Date("2000-01-01"),
                                 TRUE ~ Month >= input_variable_mod
                                 )
                       ) %>%
                pivot_longer(cols = c(Adults, Children, Households),
                             names_to = "Group",
                             values_to = "Value"
                             ) %>%
                ggplot(aes(Month, Value, group = Group, col = Group)) +
                geom_line() +
                theme_bw() +
                ylab("Number"))
      
        }
    
    )
```

### Monthly Requests

```{r Plot monthly request type}
renderPlotly(
  
    {
      
      ggplotly(
        plot_monthly_requests <- data_monthly  %>%
          left_join(new_and_frequent_households, by = "Month") %>%
          # mutate("input_variable_mod" = ifelse(grepl("20", input$variable_month),
          #                                      lubridate::my(input$variable_month), 
          #                                      NA
          #                                      )
          #        ) %>%
          # filter(case_when(input$variable_month == "Last 3 months" 
          #                    ~ Month > report_month - months(3),
          #                  input$variable_month == "Last 6 months" 
          #                    ~ Month > report_month - months(6),
          #                  input$variable_month == "Last 12 months" 
          #                    ~ Month > report_month - years(1),
          #                  input$variable_month == "All time"
          #                    ~ Month > as.Date("2000-01-01"),
          #                  TRUE ~ Month >= input_variable_mod
          #                  )
          #        ) %>%
          mutate("Returning and Frequent" = `Frequent Households` - `New and Frequent Households`,
                 "New and Infrequent" = `New Households` - `New and Frequent Households`,
                 "Returning and Infrequent" = Households - `Returning and Frequent` - `New and Frequent Households` - `New and Infrequent`) %>%
          rename("New and Frequent" = `New and Frequent Households`) %>%
          select(-Households) %>%
          pivot_longer(cols = c(`Returning and Frequent`, `New and Frequent`, `New and Infrequent`, `Returning and Infrequent`),
                       names_to = "Households",
                       values_to = "Value"
                       ) %>%
          ggplot(aes(Month, Value, fill = Households)) +
          geom_bar(stat = "identity") +
          theme_bw() +
          ylab("Number") + scale_fill_manual(values = c("#E69F00", "#CC09B3", "#68228B", "#5CACEE")))
      
        }
    
    )
```



Weekly SPC charts
===



Column {.sidebar data-width=200}
-----------------------------------------------------------------------

```{r Dropdown for SPC}
selectInput("variable_spc",
            label = "Metric",
            choices = c("Adults", "Children", "Households"),
            selected = "Adults"
            )
```

Column {data-width=400}
-----------------------------------------------------------------------

```{r Weekly plot}
### Weekly requests
data_historic_week <- data_historic %>%
  filter(Date < as.Date("2023-04-01")) %>%
  mutate("Week" = floor_date(Date, unit = "week") + days(1)) %>%
  summarise(across(.cols = c(Adults, Children, Households), 
                   .fns = ~ sum(., na.rm = TRUE)
                   ),
            .by = Week
            ) %>%
  mutate(Requests = NA)

data_weekly <- data_wrangle %>%
  summarise(across(.cols = c(Adults, Children), .fns = ~ sum(., na.rm = TRUE)),
            across(.cols = ID, .fns = ~ n_distinct(.), .names = "Households"),
            across(.cols = Date, .fns = ~ n(), .names = "Requests"),
            .by = Week
            ) %>%
  rbind(data_historic_week)

data_weekly_spc <- data_weekly %>%
  filter(Week < report_month)
```

### SPC Chart
```{r Weekly SPC}
renderPlotly(
  
  {
    
    data_weekly_spc %>%
      ptd_spc(value_field = !!sym(input$variable_spc),
              date_field = Week,
              improvement_direction = "decrease"
              ) %>%
      ptd_create_plotly(point_size = 2,
                        x_axis_date_format = "%b %Y",
                        x_axis_breaks = "1 months"
                        )
    
  }
  
)
```

Column {data-width=100}
-----------------------------------------------------------------------
### Summary
There is no special cause for concern for the number of Adults, Children or 
Households for the last month.

For more information on SPC please see:
```{r}
cat(str_replace_all("C://Users/ridge/OneDrive/Documents/Anya/making-data-count-getting-started-2019.pdf", 
                "/",
                "\\\\"))
```




Other
===
Column {.sidebar data-width=200}
-----------------------------------------------------------------------

```{r Drop down for weekly}
months <- data_wrangle %>%
  pull(Month) %>%
  unique() %>%
  format("%b %Y") %>%
  as.character()

selectInput("variable_week",
            label = "Month",
            choices = c(months, "Last 3 months", "Last 6 months", "Last 12 months", "All time"),
            selected = "Last 3 months"
            )
```

Column {data-width=100}
-----------------------------------------------------------------------

```{r Weekly averages}
renderTable(
  
  {
    
    data_weekly %>%
      mutate("input_variable_mod" = ifelse(grepl("20", input$variable_week),
                                           lubridate::my(input$variable_week), 
                                           NA
                                           )
             ) %>%
      filter(case_when(input$variable_week == "Last 3 months" 
                         ~ Week > report_month - months(3),
                       input$variable_week == "Last 6 months" 
                         ~ Week > report_month - months(6),
                       input$variable_week == "Last 12 months" 
                         ~ Week > report_month - years(1),
                       input$variable_week == "All time"
                         ~ Week > as.Date("2000-01-01"),
                       TRUE ~ Week >= input_variable_mod
                       )
             ) %>%
      pivot_longer(cols = c(Adults, Children, Households, Requests),
                   names_to = "Group",
                   values_to = "value") %>%
      summarise("Mean" = mean(value) %>% round(2),
                "sd" = sd(value) %>% round(2),
                "Median" = median(value),
                "Min" = min(value),
                "Max" = max(value),
                .by = Group
                ) 
    
    }
  
  )
```

### Days

```{r Number of Requests by Day}
renderPlotly(
  {
    ggplotly(data_wrangle %>%
      mutate("input_variable_mod" = ifelse(grepl("20", input$variable_week),
                                           lubridate::my(input$variable_week), 
                                           NA
                                           ),
             "Day" = wday(Date, label = TRUE)
             ) %>%
      filter(case_when(input$variable_week == "Last 3 months" 
                         ~ Week > report_month - months(3),
                       input$variable_week == "Last 6 months" 
                         ~ Week > report_month - months(6),
                       input$variable_week == "Last 12 months" 
                         ~ Week > report_month - years(1),
                       input$variable_week == "All time"
                         ~ Week > as.Date("2000-01-01"),
                       TRUE ~ Week >= input_variable_mod
                       )
             ) %>%
        summarise(n(), .by = c(Day, Week)) %>%
        ggplot(aes(Day, `n()`, fill = Day))+
        geom_boxplot() +
        theme_bw() +
        ylab("Number of Requests")
      ) 
    
  }
  
  )
```

```{r Notes, eval = FALSE}
# Other things I'd like to add

# Date last refreshed

# Notes/explanations?

# Percentage increase

# SPC for each metric

```
